cifar_train_loader = get_data_loader('CIFAR10')
cifar_model = ModifiedResNet18().to(device)
train_model(cifar_model, cifar_train_loader, 10)
cifar_infer_loader = get_data_loader('CIFAR10', train=False)
cifar_output = infer(cifar_model, cifar_infer_loader)
print("--- Cifar10 Output before Softmax ---")
print(cifar_output)
print()
print(cifar_output.size())
print()